from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
from Crypto_data import price_action
from langchain_core.runnables import RunnableParallel
load_dotenv()

model = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash",
    max_tokens = None,
    temperature = 0.8,
    timeout = None
)

bull_prompt = PromptTemplate.from_template(
    """You are an expert Crypto Technical Analyst with a strong BULLISH bias. 
    Your objective is to read the following technical report for {asset} and build the strongest possible data-driven case for BUYING (going long).

    Guidelines:
    1. Amplify Strength: Highlight support holding, moving average breakouts (Golden Crosses), oversold conditions (RSI), and momentum expansion (MACD, Volume).
    2. Forced Rebuttal: Do NOT ignore the bearish indicators in the report. Instead, explicitly frame them as temporary "shakeouts" or healthy pullbacks that offer an optimal entry point.
    3. Risk Management: Use the universal support/resistance levels provided at the end of the report to define your trade.

    FORMAT YOUR OUTPUT:
    - **The Bull Thesis**: A concise 2-3 sentence summary of why this asset is poised to go up.
    - **Key Bullish Catalysts**: Bullet points of specific timeframes and indicators supporting the upside.
    - **Bearish Rebuttal**: Your argument for why the negative indicators in the report are just market noise.
    - **Trade Setup**: Entry zone, Primary Target (Resistance), and Invalidation Level (Stop Loss placed strictly below Support).

    Technical Report:
    {report}""",
    input_varibles = ['asset', 'report']
)

bear_prompt = PromptTemplate.from_template(
    """You are an expert Crypto Technical Analyst with a strong BEARISH bias. 
    Your objective is to read the following technical report for {asset} and build the strongest possible data-driven case for SELLING or SHORTING.

    Guidelines:
    1. Amplify Weakness: Highlight resistance rejections, moving average breakdowns (Death Crosses), overbought conditions (RSI), and momentum exhaustion (MACD, Volume).
    2. Forced Rebuttal: Do NOT ignore the bullish indicators in the report. Instead, explicitly frame them as "bull traps," dead-cat bounces, or lagging signals that are about to reverse.
    3. Risk Management: Use the universal support/resistance levels provided at the end of the report to define your trade.

    FORMAT YOUR OUTPUT:
    - **The Bear Thesis**: A concise 2-3 sentence summary of why this asset is poised to drop.
    - **Key Bearish Catalysts**: Bullet points of specific timeframes and indicators supporting the downside.
    - **Bullish Rebuttal**: Your argument for why the positive indicators in the report are misleading traps.
    - **Trade Setup**: Short Entry zone, Primary Target (Support), and Invalidation Level (Stop Loss placed strictly above Resistance).

    Technical Report:
    {report}""",
    input_varibles = ['asset', 'report']
)

master_prompt = PromptTemplate.from_template(
    """You are the Chief Investment Officer (CIO) and Master Trading Arbiter. 
    Your objective is to read a raw Technical Analysis Report, along with two heavily biased arguments (a Bull Case and a Bear Case) generated by your subordinate analysts. 

    Your job is to cut through their bias, fact-check their claims, and make the final trading decision for {asset}.

    ### INPUTS:
    RAW TECHNICAL REPORT:
    {report}

    BULL AGENT'S CASE:
    {bull_case}

    BEAR AGENT'S CASE:
    {bear_case}

    ### CIO GUIDELINES:
    1. Fact-Check First: Compare the Bull and Bear claims against the RAW TECHNICAL REPORT. If either agent hallucinates data, exaggerates an indicator, or ignores major timeframe conflicts, call it out.
    2. Assess the Weight of Evidence: Does the multi-timeframe trend align more with the Bull or the Bear? Who has the stronger argument regarding momentum and volume?
    3. The "No Trade" Option: If the market is chopping in the middle of the range, indicators are entirely mixed, or the Stop Loss is too far away, you MUST choose "NO TRADE". Capital preservation is priority #1.
    4. Risk Management: If BUY or SELL, calculate a logical Take Profit (TP) and Stop Loss (SL) strictly using the Support and Resistance levels from the raw report. Ensure the Risk-to-Reward (R:R) ratio makes mathematical sense.

    ### FORMAT YOUR OUTPUT:
    - **Fact-Check Report**: Briefly identify any flaws, exaggerations, or hallucinations in the Bull and Bear cases.
    - **Final Verdict**: [BUY / SELL / NO TRADE]
    - **The Deciding Factor**: 2-3 sentences on exactly why you chose this verdict over the alternatives.
    - **Trade Execution**:
      - Entry Zone: 
      - Take Profit (TP): 
      - Stop Loss (SL): 
      - Risk/Reward Ratio: 
      *(If NO TRADE, write "N/A" for execution fields and state exactly what price action you are waiting for).*
    """,
    input_varibles = ['asset', 'report', 'bull_case', 'bear_case']
)

parser = StrOutputParser()

parallel_chain = RunnableParallel( {
    'bull_case' : bull_prompt | model | parser,
    'bear_case' : bear_prompt | model | parser,
    'asset': lambda x: x['asset'],
    'report': lambda x: x['report']
})

chain = parallel_chain | master_prompt | model | parser
asset = "BTC/USDT"

chain.get_graph().print_ascii()
#result = chain.invoke({'asset' : asset,'report' : price_action} )

#print("\n", result)